import { Achievement } from '../types';

const achievements: Achievement[] = [
  {
    id: 'first_session',
    title: 'First Steps',
    description: 'Complete your first session',
    category: 'milestone',
    tier: 'bronze',
    icon: 'rocket',
    requirement: { type: 'sessionCount', value: 1 },
    isUnlocked: false,
    progress: 0,
  },
  {
    id: 'sessions_5',
    title: 'Getting Started',
    description: 'Complete 5 sessions',
    category: 'milestone',
    tier: 'bronze',
    icon: 'checkmark-circle',
    requirement: { type: 'sessionCount', value: 5 },
    isUnlocked: false,
    progress: 0,
  },
  {
    id: 'sessions_20',
    title: 'Session Master',
    description: 'Complete 20 sessions',
    category: 'milestone',
    tier: 'silver',
    icon: 'medal',
    requirement: { type: 'sessionCount', value: 20 },
    isUnlocked: false,
    progress: 0,
  },
  {
    id: 'sessions_50',
    title: 'Productivity Pro',
    description: 'Complete 50 sessions',
    category: 'milestone',
    tier: 'gold',
    icon: 'trophy',
    requirement: { type: 'sessionCount', value: 50 },
    isUnlocked: false,
    progress: 0,
  },
  {
    id: 'sessions_100',
    title: 'Century Club',
    description: 'Complete 100 sessions',
    category: 'milestone',
    tier: 'platinum',
    icon: 'star',
    requirement: { type: 'sessionCount', value: 100 },
    isUnlocked: false,
    progress: 0,
  },
  {
    id: 'hours_10',
    title: '10 Hour Club',
    description: 'Track 10 hours total',
    category: 'dedication',
    tier: 'bronze',
    icon: 'time',
    requirement: { type: 'totalHours', value: 10 },
    isUnlocked: false,
    progress: 0,
  },
  {
    id: 'hours_50',
    title: 'Half Century',
    description: 'Track 50 hours total',
    category: 'dedication',
    tier: 'silver',
    icon: 'stopwatch',
    requirement: { type: 'totalHours', value: 50 },
    isUnlocked: false,
    progress: 0,
  },
  {
    id: 'hours_100',
    title: 'Century Master',
    description: 'Track 100 hours total',
    category: 'dedication',
    tier: 'gold',
    icon: 'hourglass',
    requirement: { type: 'totalHours', value: 100 },
    isUnlocked: false,
    progress: 0,
  },
  {
    id: 'hours_500',
    title: 'Time Lord',
    description: 'Track 500 hours total',
    category: 'dedication',
    tier: 'platinum',
    icon: 'infinite',
    requirement: { type: 'totalHours', value: 500 },
    isUnlocked: false,
    progress: 0,
  },
  {
    id: 'streak_3',
    title: 'Consistency',
    description: 'Track for 3 days in a row',
    category: 'streak',
    tier: 'bronze',
    icon: 'flame',
    requirement: { type: 'streak', value: 3 },
    isUnlocked: false,
    progress: 0,
  },
  {
    id: 'streak_7',
    title: 'Week Warrior',
    description: 'Track for 7 days in a row',
    category: 'streak',
    tier: 'silver',
    icon: 'flash',
    requirement: { type: 'streak', value: 7 },
    isUnlocked: false,
    progress: 0,
  },
  {
    id: 'streak_14',
    title: 'Fortnight Fighter',
    description: 'Track for 14 days in a row',
    category: 'streak',
    tier: 'gold',
    icon: 'thunderstorm',
    requirement: { type: 'streak', value: 14 },
    isUnlocked: false,
    progress: 0,
  },
  {
    id: 'streak_30',
    title: 'Monthly Master',
    description: 'Track for 30 days in a row',
    category: 'streak',
    tier: 'gold',
    icon: 'star',
    requirement: { type: 'streak', value: 30 },
    isUnlocked: false,
    progress: 0,
  },
  {
    id: 'streak_100',
    title: 'Unstoppable',
    description: 'Track for 100 days in a row',
    category: 'streak',
    tier: 'platinum',
    icon: 'diamond',
    requirement: { type: 'streak', value: 100 },
    isUnlocked: false,
    progress: 0,
  },
  {
    id: 'long_session_60',
    title: 'Marathon Session',
    description: 'Complete a session of 60+ minutes',
    category: 'dedication',
    tier: 'bronze',
    icon: 'timer',
    requirement: { type: 'longestSession', value: 60 },
    isUnlocked: false,
    progress: 0,
  },
  {
    id: 'long_session_120',
    title: 'Deep Work',
    description: 'Complete a session of 120+ minutes',
    category: 'dedication',
    tier: 'silver',
    icon: 'fitness',
    requirement: { type: 'longestSession', value: 120 },
    isUnlocked: false,
    progress: 0,
  },
  {
    id: 'long_session_180',
    title: 'Ultra Focus',
    description: 'Complete a session of 180+ minutes',
    category: 'dedication',
    tier: 'gold',
    icon: 'bonfire',
    requirement: { type: 'longestSession', value: 180 },
    isUnlocked: false,
    progress: 0,
  },
  {
    id: 'early_bird',
    title: 'Early Bird',
    description: 'Complete 10 sessions before 9 AM',
    category: 'dedication',
    tier: 'bronze',
    icon: 'sunny',
    requirement: { type: 'sessionCount', value: 10 },
    isUnlocked: false,
    progress: 0,
  },
  {
    id: 'night_owl',
    title: 'Night Owl',
    description: 'Complete 10 sessions after 10 PM',
    category: 'dedication',
    tier: 'bronze',
    icon: 'moon',
    requirement: { type: 'sessionCount', value: 10 },
    isUnlocked: false,
    progress: 0,
  },
  {
    id: 'weekend_warrior',
    title: 'Weekend Warrior',
    description: 'Complete 10 sessions on weekends',
    category: 'dedication',
    tier: 'bronze',
    icon: 'beer',
    requirement: { type: 'sessionCount', value: 10 },
    isUnlocked: false,
    progress: 0,
  },
  {
    id: 'weekly_warrior',
    title: 'Weekly Streak',
    description: 'Track every day for a full week',
    category: 'streak',
    tier: 'silver',
    icon: 'calendar',
    requirement: { type: 'sessionCount', value: 7 },
    isUnlocked: false,
    progress: 0,
  },
  {
    id: 'goal_first',
    title: 'Goal Getter',
    description: 'Complete your first goal',
    category: 'milestone',
    tier: 'bronze',
    icon: 'flag',
    requirement: { type: 'sessionCount', value: 1 },
    isUnlocked: false,
    progress: 0,
  },
  {
    id: 'goal_3',
    title: 'Goal Crusher',
    description: 'Complete 3 goals',
    category: 'milestone',
    tier: 'silver',
    icon: 'ribbon',
    requirement: { type: 'sessionCount', value: 3 },
    isUnlocked: false,
    progress: 0,
  },
  {
    id: 'goal_10',
    title: 'Goal Master',
    description: 'Complete 10 goals',
    category: 'milestone',
    tier: 'gold',
    icon: 'podium',
    requirement: { type: 'sessionCount', value: 10 },
    isUnlocked: false,
    progress: 0,
  },
  {
    id: 'goal_25',
    title: 'Goal Legend',
    description: 'Complete 25 goals',
    category: 'milestone',
    tier: 'platinum',
    icon: 'rose',
    requirement: { type: 'sessionCount', value: 25 },
    isUnlocked: false,
    progress: 0,
  },
  {
    id: 'category_master',
    title: 'Category Master',
    description: 'Complete 10 sessions in one category',
    category: 'variety',
    tier: 'bronze',
    icon: 'albums',
    requirement: { type: 'sessionCount', value: 10 },
    isUnlocked: false,
    progress: 0,
  },
  {
    id: 'category_explorer',
    title: 'Category Explorer',
    description: 'Track sessions in 3 different categories',
    category: 'variety',
    tier: 'bronze',
    icon: 'compass',
    requirement: { type: 'categoryCount', value: 3 },
    isUnlocked: false,
    progress: 0,
  },
  {
    id: 'category_diversity',
    title: 'Well Rounded',
    description: 'Track sessions in 5 different categories',
    category: 'variety',
    tier: 'silver',
    icon: 'color-palette',
    requirement: { type: 'categoryCount', value: 5 },
    isUnlocked: false,
    progress: 0,
  },
  {
    id: 'focused_sessions',
    title: 'Focus Master',
    description: 'Complete 20 sessions of 45+ minutes',
    category: 'dedication',
    tier: 'silver',
    icon: 'eye',
    requirement: { type: 'sessionCount', value: 20 },
    isUnlocked: false,
    progress: 0,
  },
];

const uniqueIds = new Set<string>();
achievements.forEach(achievement => {
  if (uniqueIds.has(achievement.id)) {
    console.error(`Duplicate achievement ID detected: ${achievement.id}`);
  }
  uniqueIds.add(achievement.id);
});

export const ACHIEVEMENT_DEFINITIONS: Achievement[] = achievements;